# .readthedocs.yml
version: 2

formats: 
    - epub
    - pdf
    - htmlzip

# python:
#     version: 3.7
#     install:
#         - requirements: docs/requirements.txt
#         - method: setuptools
#     system_packages: false

build:
  image: latest
 
conda:
    environment: docs/conda.yml
